# Generated by Django 2.0 on 2018-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='saving',
            field=models.IntegerField(default=0),
        ),
    ]
