# Generated by Django 2.0 on 2018-02-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madadju', '0005_auto_20180204_1414'),
        ('modir', '0002_admin_saving'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('receipt_number', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('ماهیانه', '1'), ('دفعه ای', '2')], default='ماهیانه', max_length=10)),
                ('madadju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadju.Madadju')),
            ],
        ),
    ]
