# Generated by Django 2.0 on 2018-02-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadju', '0002_madadju_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadju',
            name='gender',
            field=models.CharField(choices=[('مرد', 'Male'), ('زن', 'Female')], default='مرد', max_length=10),
        ),
    ]
