# Generated by Django 2.0 on 2018-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadju', '0003_auto_20180203_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='madadju',
            name='percent',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='madadju',
            name='using',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='madadju',
            name='gender',
            field=models.CharField(choices=[('مرد', 'Male'), ('زن', 'Female')], default='مرد', max_length=1),
        ),
    ]
