# Generated by Django 2.0.1 on 2018-02-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadju', '0005_auto_20180204_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='madadju',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
