# Generated by Django 2.0 on 2018-02-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamyar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_method', models.IntegerField(choices=[(1, 'email'), (0, 'text')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karbar.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFoundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('hamyar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hamyar.Hamyar')),
            ],
        ),
    ]
