# Generated by Django 2.0 on 2018-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0002_auto_20180202_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('ماهیانه', '1'), ('دفعه ای', '2')], default='ماهیانه', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.IntegerField(default=0),
        ),
    ]
