# Generated by Django 2.0 on 2018-02-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madadju', '0005_auto_20180204_1414'),
        ('madadkar', '0001_initial'),
        ('hamyar', '0003_auto_20180204_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='hamyar',
            name='report_method',
            field=models.IntegerField(choices=[(1, 'email'), (0, 'text')]),
        ),
        migrations.AddField(
            model_name='gift',
            name='hamyar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hamyar.Hamyar'),
        ),
        migrations.AddField(
            model_name='gift',
            name='madadju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadju.Madadju'),
        ),
        migrations.AddField(
            model_name='gift',
            name='madadkar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='madadkar.Madadkar'),
        ),
    ]
