# Generated by Django 2.0 on 2018-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0005_auto_20180204_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamyar',
            name='report_method',
            field=models.IntegerField(choices=[(1, 'email'), (0, 'text')]),
        ),
    ]
