# Generated by Django 2.0 on 2018-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0009_auto_20180205_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamyar',
            name='report_method',
            field=models.IntegerField(choices=[(1, 'email'), (0, 'text')]),
        ),
    ]
